name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Build
        run: go build -o ../bin/workshop -v .workshop-service/...
      - name: Test with the Go CLI
        run: go test
      - name: Upload /bin folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workshop
          path: bin/
          retention-days: 1